spring:
  redis:
    host: 192.168.1.84
    port: 6379
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employees?useSSL=true
    username: root
    password: 19811981
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  session:
    store-type: redis
  security:
    user:
      password: password


logging:
  level:
    com:
      example:
        sessiondemo: trace
    org:
      springframework:
        security: trace
        session: debug
#          data: trace
        data:
          redis: trace
#local:
#  server:
#    port: 18080
server:
  port: 18080
